taxonomies:
  registry_item_status:
    -
      vid: registry_item_status
      tid: '1'
      langcode: en
      name: accepted
      description__value: "<p>http://linked.data.gov.au/def/reg-status/accepted</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '0'
      uuid: 62894a33-4dc9-4544-8ddb-c9a99fb7709b
    -
      vid: registry_item_status
      tid: '2'
      langcode: en
      name: deprecated
      description__value: "<p>http://linked.data.gov.au/def/reg-status/deprecated</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '1'
      uuid: 8e4a56dd-be4d-47e6-8aed-b89d26c8c2a9
    -
      vid: registry_item_status
      tid: '3'
      langcode: en
      name: retired
      description__value: "<p>http://linked.data.gov.au/def/reg-status/retired</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '2'
      uuid: 7347f795-294d-4b1f-bb95-5b2a3013dca7
    -
      vid: registry_item_status
      tid: '4'
      langcode: en
      name: superseded
      description__value: "<p>http://linked.data.gov.au/def/reg-status/superseded</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '2'
      uuid: d2d8bc98-f709-49b7-8c4e-7953e1fca0d6
    -
      vid: registry_item_status
      tid: '5'
      langcode: en
      name: valid
      description__value: "<p>http://linked.data.gov.au/def/reg-status/valid</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '1'
      uuid: 10a6300e-d8df-474d-86c6-53ec39a80cf8
    -
      vid: registry_item_status
      tid: '6'
      langcode: en
      name: experimental
      description__value: "<p>http://linked.data.gov.au/def/reg-status/experimental</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '5'
      uuid: e2487d5b-c085-4c36-8b2a-4530c1a026fa
    -
      vid: registry_item_status
      tid: '7'
      langcode: en
      name: stable
      description__value: "<p>http://linked.data.gov.au/def/reg-status/stable</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '5'
      uuid: a511d578-565e-40bd-8f33-df8f06b15c7f
    -
      vid: registry_item_status
      tid: '8'
      langcode: en
      name: 'not accepted'
      description__value: "<p>http://linked.data.gov.au/def/reg-status/notAccepted</p>\r\n"
      description__format: basic_html
      weight: '8'
      parent: '0'
      uuid: 34908ea1-963b-4698-9930-cb155bf724f7
    -
      vid: registry_item_status
      tid: '9'
      langcode: en
      name: invalid
      description__value: "<p>http://linked.data.gov.au/def/reg-status/invalid</p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '8'
      uuid: 7d3cdf2b-0673-4f9c-8d08-4162f89082ba
    -
      vid: registry_item_status
      tid: '10'
      langcode: en
      name: reserved
      description__value: "<p>http://linked.data.gov.au/def/reg-status/reserved</p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '8'
      uuid: 2c862b5e-d069-4c67-aa59-2125e8951681
    -
      vid: registry_item_status
      tid: '11'
      langcode: en
      name: submitted
      description__value: "<p>http://linked.data.gov.au/def/reg-status/submitted</p>\r\n"
      description__format: basic_html
      weight: '2'
      parent: '8'
      uuid: 0ba03a46-b3af-4721-af0c-7e59b46881e7
  tags: {  }
