taxonomies:
  registry_item_status:
    -
      vid: registry_item_status
      tid: '1'
      langcode: en
      name: Accepted
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/accepted\">https://linked.data.gov.au/def/reg-statuses/accepted</a></p>\r\n"
      description__format: basic_html
      weight: '3'
      parent: '0'
      uuid: 62894a33-4dc9-4544-8ddb-c9a99fb7709b
      path: /taxonomy/term/1
      alias: /reg-statuses/accepted
    -
      vid: registry_item_status
      tid: '2'
      langcode: en
      name: Deprecated
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/deprecated\">https://linked.data.gov.au/def/reg-statuses/deprecated</a></p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '1'
      uuid: 8e4a56dd-be4d-47e6-8aed-b89d26c8c2a9
      path: /taxonomy/term/2
      alias: /reg-statuses/deprecated
    -
      vid: registry_item_status
      tid: '3'
      langcode: en
      name: Retired
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/retired\">https://linked.data.gov.au/def/reg-statuses/retired</a></p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '2'
      uuid: 7347f795-294d-4b1f-bb95-5b2a3013dca7
      path: /taxonomy/term/3
      alias: /reg-statuses/retired
    -
      vid: registry_item_status
      tid: '4'
      langcode: en
      name: Superseded
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/superseded\">https://linked.data.gov.au/def/reg-statuses/superseded</a></p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '2'
      uuid: d2d8bc98-f709-49b7-8c4e-7953e1fca0d6
      path: /taxonomy/term/4
      alias: /reg-statuses/superseded
    -
      vid: registry_item_status
      tid: '5'
      langcode: en
      name: Valid
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/valid\">https://linked.data.gov.au/def/reg-statuses/valid</a></p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '1'
      uuid: 10a6300e-d8df-474d-86c6-53ec39a80cf8
      path: /taxonomy/term/5
      alias: /reg-statuses/valid
    -
      vid: registry_item_status
      tid: '6'
      langcode: en
      name: Experimental
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/experimental\">https://linked.data.gov.au/def/reg-statuses/experimental</a></p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '5'
      uuid: e2487d5b-c085-4c36-8b2a-4530c1a026fa
      path: /taxonomy/term/6
      alias: /reg-statuses/experimental
    -
      vid: registry_item_status
      tid: '7'
      langcode: en
      name: Stable
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/stable\">https://linked.data.gov.au/def/reg-statuses/stable</a></p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '5'
      uuid: a511d578-565e-40bd-8f33-df8f06b15c7f
      path: /taxonomy/term/7
      alias: /reg-statuses/stable
    -
      vid: registry_item_status
      tid: '8'
      langcode: en
      name: 'Not Accepted'
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/notAccepted\">https://linked.data.gov.au/def/reg-statuses/notAccepted</a></p>\r\n"
      description__format: basic_html
      weight: '12'
      parent: '0'
      uuid: 34908ea1-963b-4698-9930-cb155bf724f7
      path: /taxonomy/term/8
      alias: /reg-statuses/notAccepted
    -
      vid: registry_item_status
      tid: '9'
      langcode: en
      name: Invalid
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/invalid\">https://linked.data.gov.au/def/reg-statuses/invalid</a></p>\r\n"
      description__format: basic_html
      weight: '0'
      parent: '8'
      uuid: 7d3cdf2b-0673-4f9c-8d08-4162f89082ba
      path: /taxonomy/term/9
      alias: /reg-statuses/invalid
    -
      vid: registry_item_status
      tid: '10'
      langcode: en
      name: Reserved
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/reserved\">https://linked.data.gov.au/def/reg-statuses/reserved</a></p>\r\n"
      description__format: basic_html
      weight: '1'
      parent: '8'
      uuid: 2c862b5e-d069-4c67-aa59-2125e8951681
      path: /taxonomy/term/10
      alias: /reg-statuses/reserved
    -
      vid: registry_item_status
      tid: '11'
      langcode: en
      name: Submitted
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/submitted\">https://linked.data.gov.au/def/reg-statuses/submitted</a></p>\r\n"
      description__format: basic_html
      weight: '2'
      parent: '8'
      uuid: 0ba03a46-b3af-4721-af0c-7e59b46881e7
      path: /taxonomy/term/11
      alias: /reg-statuses/submitted
    -
      vid: registry_item_status
      tid: '13'
      langcode: en
      name: Unstable
      description__value: "<p><a href=\"https://linked.data.gov.au/def/reg-statuses/unstable\">https://linked.data.gov.au/def/reg-statuses/unstable</a></p>\r\n"
      description__format: basic_html
      weight: '2'
      parent: '2'
      uuid: 22c47c53-e00b-41a9-929f-8013a7df9a81
      path: /taxonomy/term/13
      alias: /reg-statuses/unstable
  tags: {  }
