<?php

/**
 * @file
 * feedback form_alter and mail_alter hook functions for lst_agldwg.
 *
 * @ingroup lst_agldwg
 */

/**
 * Implements hook_mail_alter to prepend '[LD-Registry] ' to
 * the subject line of all outgoing emails.
 */
function lst_agldwg_mail_alter(&$message) {
    if (isset($message['subject'])) {
        $message['subject'] = '[LD Registry] ' . $message['subject'];
    } else {
        $message['subject'] = '[LD Registry]';
    }
}

/**
 * Implements hook_form_FORM_ID_alter to support prefilling subject
 * on the contact form when a query parameter 'subject' is supplied.
 */
function lst_agldwg_form_contact_message_feedback_form_alter(&$form,
                                                     $form_state,
                                                     $form_id) {
    if (!empty($_GET['subject'])) {
        $form['subject']['widget'][0]['value']['#default_value'] =
            $_GET['subject'];
    }
}
