<?php

/**
 * @file
 * feedback form_alter and mail_alter hook functions for lst_agldwg.
 *
 * @ingroup lst_agldwg
 */

/**
 * Implements hook_mail_alter to prepend '[LD-Registry] ' to
 * the subject line of all outgoing emails.
 */
function lst_agldwg_mail_alter(&$message) {
    if (isset($message['subject'])) {
        $message['subject'] = '[LD Registry] ' . $message['subject'];
    } else {
        $message['subject'] = '[LD Registry]';
    }
}

/**
 * Implements hook_form_FORM_ID_alter to support prefilling subject
 * (and possibly also the message)
 * on the contact form when a query parameter 'subject' is supplied.
 */
function lst_agldwg_form_contact_message_feedback_form_alter(&$form,
                                                             $form_state,
                                                             $form_id) {
    if (!empty($_GET['subject'])) {
        $subject = $_GET['subject'];
        $form['subject']['widget'][0]['value']['#default_value'] =
            $subject;
        // Support prefilling of the message field for the
        // subject "Organisation+registration+request".
        if ($subject == 'Organisation registration request') {
            $form['message']['widget'][0]['value']['#default_value'] =
                'Request for new Organisation Register Item

Please complete the following form.
A member of the AGLDWG will contact you if further information is required.


Name of organisation:

Alternative names (e.g., acronyms, prior names of the organisation):

Is the organisation a unit/section of another organisation?
If so, please specify:

Organisation homepage URL:

Identifiers, if available:

AGOR:

CRS:

GRID:

ROR:

';

        }
    }
}

/**
 * Implements hook_form_alter for content types.
 * Limit allowed reviewers to members of the Administrator and
 * Control body roles, and any existing value for the field.
 * Increase the height of the select list to 10,
 * so that users don't need to scroll to see all of the allowed values.
 * Remove comment settings for non-administrator users.
 */
function lst_agldwg_form_alter(&$form, $form_state, $form_id) {
    // \Drupal::logger('agldwg module')->notice('in form alter');
    // Only modify forms that have a "field_reviewer" field.
    if (!empty($form['field_reviewer'])) {
        // The array of options (i.e., all users) is:
        //   $form['field_reviewer']['widget']['#options']
        //      =>
        //        array (
        //        0 => 'Anonymous',
        //        1 => 'admin',
        //        ...)
        // The array of current values of the field is:
        //   $form['field_reviewer']['widget']['#default_value']
        //      =>
        //        array (
        //        0 => '6',
        //        )
        // The allowed users are those who are in the administrator
        // and control body roles, _and_ those who are already set
        // as reviewers of this node. (This allows for someone to continue
        // to be a reviewer who _was_ in the control body, but is no longer.)
        $allowed_users = lst_agldwg_get_admin_and_control_body_uids();
        // Add in the current values:
        if (!empty($form['field_reviewer']['widget']['#default_value'])) {
            foreach ($form['field_reviewer']['widget']['#default_value']
                     as $r) {
                $allowed_users[$r] = $r;
            }
        }
        $not_allowed_users = array_diff_key(
            $form['field_reviewer']['widget']['#options'],
            $allowed_users);
        $form['field_reviewer']['widget']['#options'] =
            array_diff($form['field_reviewer']['widget']['#options'],
                       $not_allowed_users);
        // And while we're here, make the select list bigger, so that you
        // don't need to scroll to see all the options.
        $form['field_reviewer']['widget']['#size'] = 10;
    }
    // Only modify forms that have a "field_workflow" field.
    if (!empty($form['field_workflow'])) {
        // If the current user is not an administrator,
        // remove the comment settings.
        if (!\Drupal::currentUser()->hasPermission(
            'administer site configuration')) {
            unset($form['field_workflow']);
        }
    }
}

/**
 * Helper function to get the uids of all users who are members
 * of either the Administrator or Control Body roles.
 */
function lst_agldwg_get_admin_and_control_body_uids() {
    $query = \Drupal::entityTypeManager()->getStorage('user')->getQuery();
    $uids = $query
        ->condition('status', '1')
        ->condition('roles', array('administrator', 'control_body'), 'IN')
        ->execute();
    return $uids;
    // The return value looks like:
    //   array (
    //   1 => '1',
    //   9 => '9',
    //   10 => '10',
    //   11 => '11',
    //   34 => '34',
    //   50 => '50',
    //   )
}
